log:
  path: 'log/'
  level: 'DEBUG'
  format:
    NOTSET: "[%(levelname)-7s] | %(name)-12s | %(asctime)-10s | %(message)s"
    DEBUG: "[%(levelname)-7s] | %(name)-12s | %(asctime)-10s | %(module)-15s | %(lineno)-5d | %(funcName)-15s | %(process)-7d | %(message)s"
    INFO: "[%(levelname)-7s] | %(name)-12s | %(asctime)-10s | %(message)s"
    WARNING: "[%(levelname)-7s] | %(name)-12s | %(asctime)-10s | %(module)-10s | %(lineno)-5d | %(funcName)-10s | %(message)s"
    ERROR: "[%(levelname)-7s] | %(name)-12s | %(asctime)-10s | %(module)-10s | %(lineno)-5d | %(funcName)-10s | %(message)s"
    CRITICAL: "[%(levelname)-7s] | %(name)-12s | %(asctime)-10s | %(module)-10s | %(lineno)-5d | %(funcName)-10s | %(message)s"
  file:
    enable: true
    level: 'DEBUG'
  console:
    enable: true
    level: 'INFO'
  mail:
    enable: true
    level: 'INFO'

db:
  mysql:
    host: ''
    username: ''
    password: ''
    db: ''

mail:
  smtp:
    host: ''
    username: ''
    password: ''
    port: ''
    debug: false
